### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor when running Simple File Example

### ISSUE THREAD

**Issue by lezwon** [YoSTEALTH/Liburing#13]
Hi,
I get the following error when I run the `Simple File Example`.

```
Traceback (most recent call last):
  File "test.py", line 74, in <module>
    main()
  File "test.py", line 58, in main
    fd = open(ring, cqes, 'liburing-test-file.txt', os.O_CREAT | os.O_RDWR)
  File "test.py", line 12, in open
    return _submit_and_wait(ring, cqes)  # returns fd
  File "test.py", line 44, in _submit_and_wait
    result = trap_error(cqe.res)  # auto raise appropriate exception if failed
  File "/home/ubuntu/.local/lib/python3.8/site-packages/liburing/wrapper.py", line 27, in trap_error
    raise OSError(-no, strerror(-no))
OSError: [Errno 9] Bad file descriptor 
```

Could you help me out?

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

```
5.4.0-1038-aws
```

**Comment by YoSTEALTH** [comment]
Hey @lezwon 

`io_uring_prep_openat` used in sample is a `linux 5.6` feature. https://unixism.net/loti/ref-liburing/submission.html?highlight=io_uring_prep_openat#c.io_uring_prep_openat

**Comment by lezwon** [comment]
@YoSTEALTH thank you 😊 will try it out with 5.6+ 👍
