### ISSUE TITLE
Install error on linux 5.4 

### ISSUE THREAD

**Issue by mjsML** [YoSTEALTH/Liburing#14]
When I try to install, I get the following error:
```shell
pip install --upgrade install git+https://github.com/YoSTEALTH/Liburing
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/YoSTEALTH/Liburing
  Cloning https://github.com/YoSTEALTH/Liburing to /tmp/pip-req-build-wn4o9acz
  Running command git clone -q https://github.com/YoSTEALTH/Liburing /tmp/pip-req-build-wn4o9acz
  Resolved https://github.com/YoSTEALTH/Liburing to commit 9c3d8faf7b564a3b189b2bf0ca7dfe3c3cb7e1ac
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/mjs/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpl2jd4zxj
       cwd: /tmp/pip-req-build-wn4o9acz
  Complete output (20 lines):
  Traceback (most recent call last):
    File "/home/mjs/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/mjs/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/mjs/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/usr/local/lib/python3.8/dist-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/usr/local/lib/python3.8/dist-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/usr/local/lib/python3.8/dist-packages/setuptools/build_meta.py", line 258, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/usr/local/lib/python3.8/dist-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 3, in <module>
      from liburing import skip_os
    File "/tmp/pip-req-build-wn4o9acz/liburing/__init__.py", line 1, in <module>
      from ._liburing import ffi, lib  # noqa
  ModuleNotFoundError: No module named 'liburing._liburing'
  ----------------------------------------
WARNING: Discarding git+https://github.com/YoSTEALTH/Liburing. Command errored out with exit status 1: /usr/bin/python3 /home/mjs/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpl2jd4zxj Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/bin/python3 /home/mjs/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpl2jd4zxj Check the logs for full command output.

```
and my OS info:
```shell
uname -r   
5.4.0-1043-gcp
```

**Comment by YoSTEALTH** [comment]
@mjsML Thanks for reporting https://github.com/YoSTEALTH/Liburing/commit/f17cec63a7bc4e8328583e1c985345f7a0a16400 that should fix it.

**Comment by mjsML** [comment]
Yes it did ... Thank you!
